### ISSUE TITLE
Breeding Bird Survey

### ISSUE THREAD

**Issue by ethanwhite** [weecology/ecology-data-cache#1]

**Comment by ethanwhite** [comment]
Done.

**Comment by davharris** [comment]
Did you get everything on the FTP server, or just the stuff we tend to use?

**Comment by ethanwhite** [comment]
Raw data files for the standard and 50 stop data from the Data Retriever. If there is other stuff to grab definitely reopen and add to the `breed-bird-survey` directory on the T drive.

**Comment by davharris** [comment]
The safest thing would be to operate on the assumption that USGS won't exist in its current form in 6 months.

I'm not a member of this repo, so I can't reopen.

**Comment by davharris** [comment]
Honestly, if the disk space is available, it wouldn't be a bad idea for someone to download the entire `ftp://ftpext.usgs.gov/` folder.

**Comment by ethanwhite** [comment]
> I'm not a member of this repo, so I can't reopen.

Oops, sorry. I'd added the full Weecology team but accidentally set permissions to read instead of write. That's fixed now.

I agree that we should get everything of use. There's a lot of duplication in the BBS folders (e.g., split out by taxon vs. split out by state, etc. but if there's more useful non-redundant stuff let's definitely get it.

There's about 6 TB on the T drive at the moment and I'll push for more if we start to fill it.
